### ISSUE TITLE
Bug about node-gyp when I "npm install"

### ISSUE THREAD

**Issue by ho1234c** [kosslab-kr/gitCodeShare.com#23]
If use pyenv and don't select any python, you facing this error even though you installed python in the system. I think it is to be a related with node-gyp.

```sh
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/jonghojeong/.pyenv/shims/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack pyenv: python2: command not found
gyp ERR! stack 
gyp ERR! stack The `python2' command exists in these Python versions:
gyp ERR! stack   2.7.6
gyp ERR! stack   2.7.6/envs/test
gyp ERR! stack   2.7.8
gyp ERR! stack   2.7.8/envs/dietnote_server
gyp ERR! stack   dietnote_server
gyp ERR! stack   test
gyp ERR! stack 
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:567:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/jonghojeong/source/gitCodeShare.com/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/jonghojeong/source/gitCodeShare.com/node_modules/node-sass
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

I solved this problem through select python version in pyenv like this.
```sh
pyenv shell "PYTHON VERSION YOU WANT"
```

**Comment by gimdongwoo** [comment]
It's not a bug. You need to python2 for `node-sass`.

Good catch!
